### ISSUE TITLE
Can not find "deep_fashion_3d_point_cloud_nnnotations" folder

### ISSUE THREAD

**Issue by han324** [kv2000/deepFashion3D#4]
Hello, thanks for sharing the amazing dataset.

I have downloaded "deep_fashion_3d_point_cloud.rar" and successfully unziped the file with the passcode that provided via email. 

However, I could not find the folder named "deep_fashion_3d_point_cloud_nnnotations"  as mentioned in README page.

Maybe it hasn't been published yet?

**Comment by LiuXinqi12** [comment]
H, have you got this dataset(deep_fashion_3d_point_cloud_nnnotations)?
